import { PastelThemeConfig, PastelThemeId } from '../types';

export const PASTEL_THEMES: Record<PastelThemeId, PastelThemeConfig> = {
  sky: {
    id: 'sky',
    name: 'Morning Sky',
    dotColor: '#93C5FD',
    bgMain: '#F2F6FA',
    bgSecondary: '#E5EEF6',
    cardBg: '#FFFFFF',
    cardBorder: '#DDE7F0',
    textPrimary: '#0F172A',
    textSecondary: '#475569',
    textMuted: '#94A3B8',
    accent: '#2563EB',
    accentLight: '#60A5FA',
    accentBorder: '#BFDBFE',
    badgeBg: '#DBEAFE',
    badgeText: '#1E40AF',
    particleColor: 'rgba(59, 130, 246, ALPHA)',
    waveColor: 'rgba(37, 99, 235, ALPHA)',
  },
  sage: {
    id: 'sage',
    name: 'Sage & Mint',
    dotColor: '#86EFAC',
    bgMain: '#F2F7F4',
    bgSecondary: '#E3EDE7',
    cardBg: '#FFFFFF',
    cardBorder: '#D8E5DC',
    textPrimary: '#062817',
    textSecondary: '#2D4A3E',
    textMuted: '#6B8579',
    accent: '#059669',
    accentLight: '#34D399',
    accentBorder: '#A7F3D0',
    badgeBg: '#D1FAE5',
    badgeText: '#065F46',
    particleColor: 'rgba(16, 185, 129, ALPHA)',
    waveColor: 'rgba(5, 150, 105, ALPHA)',
  },
  lavender: {
    id: 'lavender',
    name: 'Lilac & Lavender',
    dotColor: '#C4B5FD',
    bgMain: '#F6F4FB',
    bgSecondary: '#EBE5F7',
    cardBg: '#FFFFFF',
    cardBorder: '#E0D7F2',
    textPrimary: '#1E1633',
    textSecondary: '#4A3E66',
    textMuted: '#8A7B9F',
    accent: '#7C3AED',
    accentLight: '#A78BFA',
    accentBorder: '#DDD6FE',
    badgeBg: '#EDE9FE',
    badgeText: '#5B21B6',
    particleColor: 'rgba(139, 92, 246, ALPHA)',
    waveColor: 'rgba(124, 58, 237, ALPHA)',
  },
  rose: {
    id: 'rose',
    name: 'Rose & Peach',
    dotColor: '#FDA4AF',
    bgMain: '#FDF5F6',
    bgSecondary: '#F8E6E9',
    cardBg: '#FFFFFF',
    cardBorder: '#F2D7DC',
    textPrimary: '#2C1319',
    textSecondary: '#5E3842',
    textMuted: '#9B747E',
    accent: '#E11D48',
    accentLight: '#FB7185',
    accentBorder: '#FECDD3',
    badgeBg: '#FFE4E6',
    badgeText: '#9F1239',
    particleColor: 'rgba(244, 63, 94, ALPHA)',
    waveColor: 'rgba(225, 29, 72, ALPHA)',
  },
  oat: {
    id: 'oat',
    name: 'Oat & Pearl',
    dotColor: '#FDE68A',
    bgMain: '#FAF8F5',
    bgSecondary: '#EFEAE1',
    cardBg: '#FFFFFF',
    cardBorder: '#E5DED2',
    textPrimary: '#292524',
    textSecondary: '#57534E',
    textMuted: '#8F8982',
    accent: '#D97706',
    accentLight: '#FBBF24',
    accentBorder: '#FDE68A',
    badgeBg: '#FEF3C7',
    badgeText: '#92400E',
    particleColor: 'rgba(217, 119, 6, ALPHA)',
    waveColor: 'rgba(180, 83, 9, ALPHA)',
  },
};
